name: prebuild

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  prebuild:
    strategy:
      matrix:
        include:
          - name: win32-x86
            os: windows-2019
            node: x86
            command: build:x86
          - name: win32-ia32
            os: windows-2019
            node: x64
            command: build:ia32
          - name: win32-x64
            os: windows-2019
            node: x64
            command: build:x64
          - name: win32-arm64
            os: windows-2022
            command: build:arm64
    name: Build ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    steps:
      - if: matrix.node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          architecture: ${{ matrix.node }}
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: yarn install --ignore-scripts
      - run: yarn ${{ matrix.command }}
      - run: tar -zcvf ${{ matrix.name }}.tar.gz -C prebuilds .
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.name }}.tar.gz
          retention-days: 1
  release:
    needs: prebuild
    name: Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - uses: softprops/action-gh-release@975c1b265e11dd76618af1c374e7981f9a6ff44a
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: artifacts/*/*.tar.gz
